language: c
sudo: false
addons:
  apt:
    packages:
      - texinfo

os:
  - osx
  - linux

osx_image: xcode6.4

compiler:
  - gcc
  - clang

script:
  - ./.build_dependencies && ./configure --with-mpir=deps --with-mpfr=deps && make -j4 && make -j4 check

